version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gii_project2_network
    volumes:
      - /home/jam2208/nginx.conf:/etc/nginx/nginx.conf
      - gii_project2_static:/data/static/
      - gii_project2_media:/data/media/

  django:
    image: gii_project2:3
    networks:
      - gii_project2_network
    volumes:
      - gii_project2_static:/home/GII_Project2/staticfiles/
      - gii_project2_media:/home/GII_Project2/media/

networks:
  gii_project2_network:

volumes:
  gii_project2_static:
  gii_project2_media: