version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gii_project2_network
    volumes:
      - /home/jam2208/nginx.conf:/etc/nginx/nginx.conf
      - gii_project2_static:/data/static/
      - gii_project2_media:/data/media/

  django:
    image: gii_project2:3
    networks:
      - gii_project2_network
    volumes:
      - gii_project2_static:/home/GII_Project2/staticfiles/
      - gii_project2_media:/home/GII_Project2/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gii_project2_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gii_project2_network:

volumes:
  gii_project2_static:
  gii_project2_media:
  mariadb_volume:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true